export const USER_LIST_URL =
  "https://my-json-server.typicode.com/karolkproexe/jsonplaceholderdb/data";

export const SELECT_USER_ID = "DASHHBOARD.SELECT_USER_ID";

export const GET_USERS_REQUEST = "DASHHBOARD.GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "DASHHBOARD.GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "DASHHBOARD.GET_USERS_FAILURE";

export const ADD_NEW_USER_REQUEST = "DASHHBOARD.ADD_NEW_USER_REQUEST";
export const ADD_NEW_USER_SUCCESS = "DASHHBOARD.ADD_NEW_USER_SUCCESS";
export const ADD_NEW_USER_FAILURE = "DASHHBOARD.ADD_NEW_USER_FAILURE";

export const EDIT_USER_REQUEST = "DASHHBOARD.EDIT_USER_REQUEST";
export const EDIT_USER_SUCCESS = "DASHHBOARD.EDIT_USER_SUCCESS";
export const EDIT_USER_FAILURE = "DASHHBOARD.EDIT_USER_FAILURE";

export const DELETE_USER_REQUEST = "DASHHBOARD.DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DASHHBOARD.DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DASHHBOARD.DELETE_USER_FAILURE";

export const OPEN_DIALOG = "COMPONENTS.OPEN_DIALOG";
export const CLOSE_DIALOG = "COMPONENTS.CLOSE_DIALOG";
